/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentProgress: typeof import('./src/components/welcome/AgentProgress.vue')['default']
    CalendarMonth: typeof import('./src/components/welcome/CalendarMonth.vue')['default']
    CatalogDrawer: typeof import('./src/components/welcome/CatalogDrawer.vue')['default']
    CountdownOverlay: typeof import('./src/components/game/CountdownOverlay.vue')['default']
    DayRideList: typeof import('./src/components/welcome/DayRideList.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    GameBubble: typeof import('./src/components/game/GameBubble.vue')['default']
    GameSummary: typeof import('./src/components/game/GameSummary.vue')['default']
    GlassesOverlay: typeof import('./src/components/game/GlassesOverlay.vue')['default']
    Hud: typeof import('./src/components/game/Hud.vue')['default']
    HudBottomLeft: typeof import('./src/components/game/HudBottomLeft.vue')['default']
    HudBottomRight: typeof import('./src/components/game/HudBottomRight.vue')['default']
    HudCameraMode: typeof import('./src/components/game/HudCameraMode.vue')['default']
    HudChart: typeof import('./src/components/game/HudChart.vue')['default']
    HudCoins: typeof import('./src/components/game/HudCoins.vue')['default']
    HudCustomizePanel: typeof import('./src/components/game/HudCustomizePanel.vue')['default']
    HudEventBar: typeof import('./src/components/game/HudEventBar.vue')['default']
    HudTopBar: typeof import('./src/components/game/HudTopBar.vue')['default']
    HudWorkoutBar: typeof import('./src/components/game/HudWorkoutBar.vue')['default']
    LoadingIntroOverlay: typeof import('./src/components/game/LoadingIntroOverlay.vue')['default']
    MapContainer: typeof import('./src/components/game/MapContainer.vue')['default']
    MarkdownView: typeof import('./src/components/welcome/MarkdownView.vue')['default']
    MessageTemplateEditor: typeof import('./src/components/welcome/MessageTemplateEditor.vue')['default']
    Minimap: typeof import('./src/components/game/Minimap.vue')['default']
    PauseOverlay: typeof import('./src/components/game/PauseOverlay.vue')['default']
    PiPSidebar: typeof import('./src/components/game/PiPSidebar.vue')['default']
    PlanBanner: typeof import('./src/components/welcome/PlanBanner.vue')['default']
    PlanSegmentProfile: typeof import('./src/components/welcome/PlanSegmentProfile.vue')['default']
    PlanWeekRamp: typeof import('./src/components/welcome/PlanWeekRamp.vue')['default']
    PowerGauge: typeof import('./src/components/game/PowerGauge.vue')['default']
    PresetDrawer: typeof import('./src/components/welcome/PresetDrawer.vue')['default']
    RideDetailDrawer: typeof import('./src/components/welcome/RideDetailDrawer.vue')['default']
    RideHistory: typeof import('./src/components/welcome/RideHistory.vue')['default']
    RidePickerDrawer: typeof import('./src/components/welcome/RidePickerDrawer.vue')['default']
    RouteCard: typeof import('./src/components/welcome/RouteCard.vue')['default']
    RouteList: typeof import('./src/components/welcome/RouteList.vue')['default']
    RoutePreviewMap: typeof import('./src/components/welcome/RoutePreviewMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./src/components/welcome/SettingsPanel.vue')['default']
    StartBar: typeof import('./src/components/welcome/StartBar.vue')['default']
    StartChecklist: typeof import('./src/components/welcome/StartChecklist.vue')['default']
    StyleTuningPanel: typeof import('./src/components/game/StyleTuningPanel.vue')['default']
    TrainingCalendar: typeof import('./src/components/welcome/TrainingCalendar.vue')['default']
    WelcomeBackdrop: typeof import('./src/components/welcome/WelcomeBackdrop.vue')['default']
    WorkoutElevationPreview: typeof import('./src/components/welcome/WorkoutElevationPreview.vue')['default']
    ZoneWarning: typeof import('./src/components/game/ZoneWarning.vue')['default']
  }
}
