/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CalendarMonth: typeof import('./src/components/welcome/CalendarMonth.vue')['default']
    CatalogTab: typeof import('./src/components/welcome/CatalogTab.vue')['default']
    DayRideList: typeof import('./src/components/welcome/DayRideList.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FileDropZone: typeof import('./src/components/welcome/FileDropZone.vue')['default']
    GameBubble: typeof import('./src/components/game/GameBubble.vue')['default']
    GameSummary: typeof import('./src/components/game/GameSummary.vue')['default']
    GlassesOverlay: typeof import('./src/components/game/GlassesOverlay.vue')['default']
    Hud: typeof import('./src/components/game/Hud.vue')['default']
    HudBottomLeft: typeof import('./src/components/game/HudBottomLeft.vue')['default']
    HudBottomRight: typeof import('./src/components/game/HudBottomRight.vue')['default']
    HudChart: typeof import('./src/components/game/HudChart.vue')['default']
    HudCoins: typeof import('./src/components/game/HudCoins.vue')['default']
    HudEventBar: typeof import('./src/components/game/HudEventBar.vue')['default']
    HudTopBar: typeof import('./src/components/game/HudTopBar.vue')['default']
    MapContainer: typeof import('./src/components/game/MapContainer.vue')['default']
    MessageTemplateEditor: typeof import('./src/components/welcome/MessageTemplateEditor.vue')['default']
    Minimap: typeof import('./src/components/game/Minimap.vue')['default']
    PiPSidebar: typeof import('./src/components/game/PiPSidebar.vue')['default']
    PlanBanner: typeof import('./src/components/welcome/PlanBanner.vue')['default']
    PresetDrawer: typeof import('./src/components/welcome/PresetDrawer.vue')['default']
    RideDetailDrawer: typeof import('./src/components/welcome/RideDetailDrawer.vue')['default']
    RideHistory: typeof import('./src/components/welcome/RideHistory.vue')['default']
    RouteCard: typeof import('./src/components/welcome/RouteCard.vue')['default']
    RouteList: typeof import('./src/components/welcome/RouteList.vue')['default']
    RoutePreviewMap: typeof import('./src/components/welcome/RoutePreviewMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./src/components/welcome/SettingsPanel.vue')['default']
    StartChecklist: typeof import('./src/components/welcome/StartChecklist.vue')['default']
    TrainingCalendar: typeof import('./src/components/welcome/TrainingCalendar.vue')['default']
    WorkoutElevationPreview: typeof import('./src/components/welcome/WorkoutElevationPreview.vue')['default']
    ZoneWarning: typeof import('./src/components/game/ZoneWarning.vue')['default']
  }
}
