import * as Vue from 'vue';
import { createApp } from 'vue';
import { createPinia } from 'pinia';

// 把 app 打包的 Vue 實例掛到 window,供 public/vue-cdn-shim.mjs 轉發給
// esm.sh 上的 md-editor-v3（見 index.html 的 import map）,確保只有一份 Vue。
(window as unknown as { __vueForCdn?: typeof Vue }).__vueForCdn = Vue;
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import {
  faGear,
  faHeart,
  faGauge,
  faBicycle,
  faBolt,
  faCoins,
  faCouch,
  faPlay,
  faPause,
  faStop,
  faUpload,
  faRotate,
  faArrowsLeftRight,
  faCheck,
  faXmark,
  faFlag,
  faClock,
  faRoute,
  faMountain,
  faWifi,
  faTriangleExclamation,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faTrash,
  faDownload,
  faSpinner,
  faTrophy,
  faMap,
  faMapLocationDot,
  faSliders,
  faTowerBroadcast,
  faMicrochip,
  faThumbtack,
  faCodeCompare,
  faFileExport,
  faClockRotateLeft,
  faCaretUp,
  faCaretDown,
  faWandMagicSparkles,
  faCloudSun,
  faCloudRain,
  faSnowflake,
  faSun,
  faCloud,
  faGlasses,
  faPaintbrush,
  faDice,
  faCube,
  faVolumeHigh,
  faHeartPulse,
  faCalendarDays,
  faChartLine,
  faGaugeHigh,
  faArrowLeft,
  faArrowRight,
  faUpRightFromSquare,
  faWindowRestore,
  faArrowTrendUp,
  faArrowTrendDown,
  faFire,
  faFlagCheckered,
  faPersonRunning,
  faHeartCircleExclamation,
  faMedal,
  faThumbsUp,
  faRoad,
  faCommentDots,
  faClipboardList,
  faCircleInfo,
  faPenToSquare,
  faRotateLeft,
  faFileImport,
  faList,
  faListCheck,
  faCirclePlay,
  faMugHot,
  faCircleCheck,
  faPlus,
  faBug,
  faScaleBalanced,
  faCloudArrowDown,
  faMagnifyingGlass,
  // Random-event + workout-segment theme icons
  faWind,
  faCircleXmark,
  faCloudShowersHeavy,
  faGem,
  faCarSide,
  faFeather,
  faMoon,
  // Render-mode picker (3D / classic / 2D)
  faMountainSun,
  faChessBoard,
  // 騎後 RPE 主觀感受臉譜(很輕鬆 → 力竭)
  faFaceGrinBeam,
  faFaceSmile,
  faFaceMeh,
  faFaceFrown,
  faFaceDizzy,
} from '@fortawesome/free-solid-svg-icons';
import { faGithub, faBluetooth } from '@fortawesome/free-brands-svg-icons';

import './styles/themes.scss';
import 'element-plus/theme-chalk/dark/css-vars.css';
// Imperative Element Plus APIs (ElMessageBox, ElMessage, ElNotification) bypass
// unplugin-vue-components, so their styles must be pulled in manually.
import 'element-plus/es/components/message-box/style/css';
import 'element-plus/es/components/message/style/css';
import 'element-plus/es/components/notification/style/css';
import 'element-plus/es/components/overlay/style/css';

import App from './App.vue';
import router from './router';

// Register Font Awesome icons
library.add(
  faGear,
  faHeart,
  faGauge,
  faBicycle,
  faBolt,
  faCoins,
  faCouch,
  faPlay,
  faPause,
  faStop,
  faUpload,
  faRotate,
  faArrowsLeftRight,
  faCheck,
  faXmark,
  faFlag,
  faClock,
  faRoute,
  faMountain,
  faWifi,
  faTriangleExclamation,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faTrash,
  faDownload,
  faSpinner,
  faTrophy,
  faMap,
  faMapLocationDot,
  faSliders,
  faTowerBroadcast,
  faMicrochip,
  faThumbtack,
  faCodeCompare,
  faFileExport,
  faClockRotateLeft,
  faCaretUp,
  faCaretDown,
  faWandMagicSparkles,
  faCloudSun,
  faCloudRain,
  faSnowflake,
  faSun,
  faCloud,
  faGlasses,
  faPaintbrush,
  faDice,
  faCube,
  faVolumeHigh,
  faHeartPulse,
  faCalendarDays,
  faChartLine,
  faGaugeHigh,
  faArrowLeft,
  faArrowRight,
  faUpRightFromSquare,
  faWindowRestore,
  faArrowTrendUp,
  faArrowTrendDown,
  faFire,
  faFlagCheckered,
  faPersonRunning,
  faHeartCircleExclamation,
  faMedal,
  faThumbsUp,
  faRoad,
  faCommentDots,
  faClipboardList,
  faCircleInfo,
  faPenToSquare,
  faRotateLeft,
  faFileImport,
  faList,
  faListCheck,
  faCirclePlay,
  faMugHot,
  faCircleCheck,
  faPlus,
  faBug,
  faScaleBalanced,
  faCloudArrowDown,
  faMagnifyingGlass,
  faWind,
  faCircleXmark,
  faCloudShowersHeavy,
  faGem,
  faCarSide,
  faFeather,
  faMoon,
  faMountainSun,
  faChessBoard,
  faFaceGrinBeam,
  faFaceSmile,
  faFaceMeh,
  faFaceFrown,
  faFaceDizzy,
  faGithub as unknown as import('@fortawesome/fontawesome-svg-core').IconDefinition,
  faBluetooth as unknown as import('@fortawesome/fontawesome-svg-core').IconDefinition,
);

document.documentElement.classList.add('dark');

const app = createApp(App);
app.use(createPinia());
app.use(router);
app.component('font-awesome-icon', FontAwesomeIcon);
app.mount('#app');

// Register tile-cache service worker for persistent map tile caching
if ('serviceWorker' in navigator) {
  navigator.serviceWorker.register('/tile-cache-sw.js').catch(() => {
    // SW registration failed — tiles will still work, just without persistent cache
  });
}
