import { createApp } from 'vue';
import { createPinia } from 'pinia';
import { library } from '@fortawesome/fontawesome-svg-core';
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome';
import {
  faGear,
  faHeart,
  faGauge,
  faBicycle,
  faBolt,
  faCoins,
  faPlay,
  faPause,
  faStop,
  faUpload,
  faRotate,
  faArrowsLeftRight,
  faCheck,
  faXmark,
  faFlag,
  faClock,
  faRoute,
  faMountain,
  faWifi,
  faTriangleExclamation,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faTrash,
  faDownload,
  faSpinner,
  faTrophy,
  faMap,
  faMapLocationDot,
  faSliders,
  faTowerBroadcast,
  faMicrochip,
  faThumbtack,
  faCodeCompare,
  faFileExport,
  faClockRotateLeft,
  faCaretUp,
  faCaretDown,
  faWandMagicSparkles,
  faCloudSun,
  faCloudRain,
  faSnowflake,
  faSun,
  faCloud,
  faGlasses,
  faCube,
  faVolumeHigh,
  faHeartPulse,
  faCalendarDays,
  faChartLine,
  faGaugeHigh,
  faArrowLeft,
  faArrowRight,
  faUpRightFromSquare,
  faArrowTrendUp,
  faArrowTrendDown,
  faFire,
  faFlagCheckered,
  faPersonRunning,
  faHeartCircleExclamation,
  faMedal,
  faThumbsUp,
  faRoad,
  faCommentDots,
  faClipboardList,
  faCircleInfo,
  faPenToSquare,
  faRotateLeft,
  faFileImport,
  faList,
  faCirclePlay,
  faMugHot,
  faCircleCheck,
  faPlus,
  faBug,
  faScaleBalanced,
  faCloudArrowDown,
  // Random-event + workout-segment theme icons
  faWind,
  faCircleXmark,
  faCloudShowersHeavy,
  faGem,
  faCarSide,
  faFeather,
  faMoon,
} from '@fortawesome/free-solid-svg-icons';
import { faGithub, faBluetooth } from '@fortawesome/free-brands-svg-icons';

import 'element-plus/theme-chalk/dark/css-vars.css';
// Imperative Element Plus APIs (ElMessageBox, ElMessage, ElNotification) bypass
// unplugin-vue-components, so their styles must be pulled in manually.
import 'element-plus/es/components/message-box/style/css';
import 'element-plus/es/components/message/style/css';
import 'element-plus/es/components/notification/style/css';
import 'element-plus/es/components/overlay/style/css';

import App from './App.vue';
import router from './router';

// Register Font Awesome icons
library.add(
  faGear,
  faHeart,
  faGauge,
  faBicycle,
  faBolt,
  faCoins,
  faPlay,
  faPause,
  faStop,
  faUpload,
  faRotate,
  faArrowsLeftRight,
  faCheck,
  faXmark,
  faFlag,
  faClock,
  faRoute,
  faMountain,
  faWifi,
  faTriangleExclamation,
  faChevronRight,
  faChevronLeft,
  faChevronDown,
  faChevronUp,
  faTrash,
  faDownload,
  faSpinner,
  faTrophy,
  faMap,
  faMapLocationDot,
  faSliders,
  faTowerBroadcast,
  faMicrochip,
  faThumbtack,
  faCodeCompare,
  faFileExport,
  faClockRotateLeft,
  faCaretUp,
  faCaretDown,
  faWandMagicSparkles,
  faCloudSun,
  faCloudRain,
  faSnowflake,
  faSun,
  faCloud,
  faGlasses,
  faCube,
  faVolumeHigh,
  faHeartPulse,
  faCalendarDays,
  faChartLine,
  faGaugeHigh,
  faArrowLeft,
  faArrowRight,
  faUpRightFromSquare,
  faArrowTrendUp,
  faArrowTrendDown,
  faFire,
  faFlagCheckered,
  faPersonRunning,
  faHeartCircleExclamation,
  faMedal,
  faThumbsUp,
  faRoad,
  faCommentDots,
  faClipboardList,
  faCircleInfo,
  faPenToSquare,
  faRotateLeft,
  faFileImport,
  faList,
  faCirclePlay,
  faMugHot,
  faCircleCheck,
  faPlus,
  faBug,
  faScaleBalanced,
  faCloudArrowDown,
  faWind,
  faCircleXmark,
  faCloudShowersHeavy,
  faGem,
  faCarSide,
  faFeather,
  faMoon,
  faGithub as unknown as import('@fortawesome/fontawesome-svg-core').IconDefinition,
  faBluetooth as unknown as import('@fortawesome/fontawesome-svg-core').IconDefinition,
);

document.documentElement.classList.add('dark');

const app = createApp(App);
app.use(createPinia());
app.use(router);
app.component('font-awesome-icon', FontAwesomeIcon);
app.mount('#app');

// Register tile-cache service worker for persistent map tile caching
if ('serviceWorker' in navigator) {
  navigator.serviceWorker.register('/tile-cache-sw.js').catch(() => {
    // SW registration failed — tiles will still work, just without persistent cache
  });
}
