/**
 * Training plan (課表) types, helpers, and validation.
 *
 * A training plan is a multi-week schedule where each day prescribes
 * a workout session (with HR-based segments) or a rest day.
 * Plans are generated by LLM or imported manually.
 */

import dayjs from 'dayjs';
import type { WorkoutSegment } from './workouts.js';

// ── Types ──

/** Training segment type */
export type SegmentType = 'warmup' | 'steady' | 'interval_work' | 'interval_rest' | 'cooldown';

/** Single training segment within a session */
export interface PlanSegment {
  type: SegmentType;
  durationMin: number;       // segment duration in minutes
  hrMin: number;             // target HR floor (bpm)
  hrMax: number;             // target HR ceiling (bpm)
  cadenceRpm?: number;       // optional cadence target
  notes?: string;            // brief coaching note
}

/** Single day's training session */
export interface PlanSession {
  day: number;               // 1-based sequential day number
  type: 'training' | 'rest';
  durationMin: number;       // total duration in minutes (0 for rest)
  segments: PlanSegment[];   // empty for rest days
}

/** One week within the plan */
export interface PlanWeek {
  week: number;              // 1-based week number
  focus: string;             // week's training focus description
  sessions: PlanSession[];   // 7 sessions (including rest days)
}

/** LLM output / import format (before adding metadata) */
export interface TrainingPlanInput {
  name: string;
  description: string;
  weeks: PlanWeek[];
}

/** Stored training plan (with metadata) */
export interface TrainingPlan {
  id: string;
  name: string;
  description: string;
  totalDays: number;
  weeks: PlanWeek[];
  createdAt: number;         // timestamp ms
  source: 'manual' | 'llm';
}

/** Summary for list views (without heavy weeks data) */
export type TrainingPlanSummary = Omit<TrainingPlan, 'weeks'>;

/** Active plan state — tracks which plan is activated and when it started */
export interface ActivePlanState {
  planId: string;
  startDate: string;         // YYYY-MM-DD, day 1 aligns to this date
}

/** Completion record for a single plan day */
export interface PlanDayCompletion {
  planId: string;
  day: number;
  rideId: number | null;     // linked ride ID, null for manual marks
  completedAt: number;       // timestamp ms
  manual: boolean;           // true = manually marked (e.g. outdoor ride)
}

// ── Segment colors (Cyberpunk palette) ──

export const SEGMENT_TYPE_COLORS: Record<SegmentType, string> = {
  warmup:         '#4a90d9',  // cold blue
  steady:         '#66bb6a',  // steady green
  interval_work:  '#ff6d00',  // neon orange
  interval_rest:  '#00e676',  // neon green
  cooldown:       '#4a90d9',  // cold blue
};

// ── Helper functions ──

/**
 * Calculate the current plan day based on the start date and today.
 * Returns 1 on the start date, 2 the next day, etc.
 */
export function getCurrentPlanDay(startDate: string): number {
  return dayjs().startOf('day').diff(dayjs(startDate).startOf('day'), 'day') + 1;
}

/**
 * Find the session for a given day number across all weeks.
 */
export function getSessionByDay(plan: TrainingPlan, day: number): PlanSession | null {
  for (const week of plan.weeks) {
    for (const session of week.sessions) {
      if (session.day === day) return session;
    }
  }
  return null;
}

/**
 * Convert PlanSegment[] to WorkoutSegment[] for use with useWorkoutTracker.
 */
export function planSegmentsToWorkoutSegments(segments: PlanSegment[]): WorkoutSegment[] {
  return segments.map((s) => ({
    name: s.notes || s.type,
    durationMs: s.durationMin * 60_000,
    targetFtpPercent: 0,
    targetCadence: s.cadenceRpm,
    color: SEGMENT_TYPE_COLORS[s.type],
    hrMin: s.hrMin,
    hrMax: s.hrMax,
  }));
}

/**
 * Convert a TrainingPlanInput (LLM output) into a storable TrainingPlan shape
 * (without id and createdAt, which are added by PlanStore).
 */
export function createPlanFromInput(
  input: TrainingPlanInput,
  source: 'manual' | 'llm',
): Omit<TrainingPlan, 'id' | 'createdAt'> {
  let totalDays = 0;
  for (const week of input.weeks) {
    for (const session of week.sessions) {
      if (session.day > totalDays) totalDays = session.day;
    }
  }
  return {
    name: input.name,
    description: input.description,
    totalDays,
    weeks: input.weeks,
    source,
  };
}

// ── Validation ──

const VALID_SEGMENT_TYPES = new Set<string>(['warmup', 'steady', 'interval_work', 'interval_rest', 'cooldown']);
const VALID_SESSION_TYPES = new Set<string>(['training', 'rest']);

/**
 * Validate a raw LLM JSON output against the TrainingPlanInput schema.
 * Returns { valid, errors } where errors lists all issues found.
 */
export function validatePlanInput(input: unknown): { valid: boolean; errors: string[] } {
  const errors: string[] = [];

  if (typeof input !== 'object' || input === null) {
    return { valid: false, errors: ['Input must be a JSON object'] };
  }

  const obj = input as Record<string, unknown>;

  if (typeof obj.name !== 'string' || obj.name.length === 0) {
    errors.push('Missing or empty "name" field');
  }
  if (typeof obj.description !== 'string') {
    errors.push('Missing "description" field');
  }
  if (!Array.isArray(obj.weeks) || obj.weeks.length === 0) {
    errors.push('Missing or empty "weeks" array');
    return { valid: false, errors };
  }

  const seenDays = new Set<number>();

  for (let wi = 0; wi < obj.weeks.length; wi++) {
    const week = obj.weeks[wi] as Record<string, unknown>;
    const wp = `weeks[${wi}]`;

    if (typeof week.week !== 'number') errors.push(`${wp}.week must be a number`);
    if (typeof week.focus !== 'string') errors.push(`${wp}.focus must be a string`);

    if (!Array.isArray(week.sessions)) {
      errors.push(`${wp}.sessions must be an array`);
      continue;
    }

    for (let si = 0; si < week.sessions.length; si++) {
      const session = week.sessions[si] as Record<string, unknown>;
      const sp = `${wp}.sessions[${si}]`;

      if (typeof session.day !== 'number' || session.day < 1) {
        errors.push(`${sp}.day must be a positive integer`);
      } else if (seenDays.has(session.day as number)) {
        errors.push(`${sp}.day ${session.day} is duplicated`);
      } else {
        seenDays.add(session.day as number);
      }

      if (!VALID_SESSION_TYPES.has(session.type as string)) {
        errors.push(`${sp}.type must be "training" or "rest"`);
      }

      if (typeof session.durationMin !== 'number') {
        errors.push(`${sp}.durationMin must be a number`);
      }

      if (!Array.isArray(session.segments)) {
        errors.push(`${sp}.segments must be an array`);
        continue;
      }

      if (session.type === 'rest' && (session.segments as unknown[]).length > 0) {
        errors.push(`${sp}: rest day must have empty segments`);
      }

      for (let sgi = 0; sgi < (session.segments as unknown[]).length; sgi++) {
        const seg = (session.segments as Record<string, unknown>[])[sgi];
        const sgp = `${sp}.segments[${sgi}]`;

        if (!VALID_SEGMENT_TYPES.has(seg.type as string)) {
          errors.push(`${sgp}.type "${seg.type}" is invalid`);
        }
        if (typeof seg.durationMin !== 'number' || (seg.durationMin as number) <= 0) {
          errors.push(`${sgp}.durationMin must be a positive number`);
        }
        if (typeof seg.hrMin !== 'number') errors.push(`${sgp}.hrMin must be a number`);
        if (typeof seg.hrMax !== 'number') errors.push(`${sgp}.hrMax must be a number`);
        if (typeof seg.hrMin === 'number' && typeof seg.hrMax === 'number' && seg.hrMin > seg.hrMax) {
          errors.push(`${sgp}.hrMin (${seg.hrMin}) > hrMax (${seg.hrMax})`);
        }
      }
    }
  }

  return { valid: errors.length === 0, errors };
}
